apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: web-containers
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/shared/nginx/html
  - name: ftp-container
    image: fauria/vsftpd
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data